[build]
  base    = "frontend"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://faceshield-edgeai-backend.onrender.com/api/v1"
  VITE_BIOMETRICS_URL = "https://faceshield-biometrics.onrender.com/api/v1"
  VITE_SOCKET_URL = "https://faceshield-edgeai-backend.onrender.com"
  VITE_TELEMETRY_URL = ""

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"
